version: '3.5'
services:
  mongo_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - crawler_db:/data/db
  rabbit:
    image: rabbitmq:${RABBIT_VERSION}

  engine:
    image: ${USER_NAME}/crawler:${CRAWLER_VERSION}
    restart: on-failure
    depends_on:
      - mongo_db
      - rabbit
    environment:
      - MONGO=mongo_db
      - RMQ_HOST=rabbit

volumes:
  crawler_db:
